//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Product Item</summary>
	[PublishedContentModel("productItem")]
	public partial class ProductItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "productItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProductItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProductItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Delivery Time
		///</summary>
		[ImplementPropertyType("deliveryTime")]
		public int DeliveryTime
		{
			get { return this.GetPropertyValue<int>("deliveryTime"); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("header")]
		public IHtmlString Header
		{
			get { return this.GetPropertyValue<IHtmlString>("header"); }
		}

		///<summary>
		/// Home Images
		///</summary>
		[ImplementPropertyType("homeImages")]
		public object HomeImages
		{
			get { return this.GetPropertyValue("homeImages"); }
		}

		///<summary>
		/// Images
		///</summary>
		[ImplementPropertyType("images")]
		public IHtmlString Images
		{
			get { return this.GetPropertyValue<IHtmlString>("images"); }
		}

		///<summary>
		/// Single box
		///</summary>
		[ImplementPropertyType("singleBox")]
		public Newtonsoft.Json.Linq.JToken SingleBox
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("singleBox"); }
		}
	}
}
